DROP TABLE COVID_REGION CASCADE CONSTRAINTS;
DROP TABLE COVID_DOMESTIC CASCADE CONSTRAINTS;

CREATE TABLE COVID_REGION(
    REGDATE CHAR(8) NOT NULL,
    REGION  CHAR(6)  NOT NULL,
    REGCASE    NUMBER  NOT NULL,
    REGDEATH   NUMBER  NOT NULL,
    
    CONSTRAINT PK_REGID PRIMARY KEY (REGDATE, REGION)
);

COMMENT ON TABLE COVID_REGION IS '지역별 코로나현황';
COMMENT ON COLUMN COVID_REGION.REGDATE IS '날짜';
COMMENT ON COLUMN COVID_REGION.REGION IS '지역';
COMMENT ON COLUMN COVID_REGION.REGCASE IS '지역 확진자';
COMMENT ON COLUMN COVID_REGION.REGDEATH IS '지역 사망자';

CREATE TABLE COVID_DOMESTIC(
    COVDATE CHAR(8) CONSTRAINT pk_domid PRIMARY KEY, /* yyyymmdd */
    DAILY_CASE  NUMBER  NOT NULL,
    TOTAL_CASE  NUMBER  NOT NULL,
    DAILY_DEATH NUMBER  NOT NULL
);

COMMENT ON TABLE COVID_DOMESTIC IS '전국 코로나 현황';
COMMENT ON COLUMN COVID_DOMESTIC.COVDATE IS '날짜';
COMMENT ON COLUMN COVID_DOMESTIC.DAILY_CASE IS '일일확진자';
COMMENT ON COLUMN COVID_DOMESTIC.TOTAL_CASE IS '누적확진자';
COMMENT ON COLUMN COVID_DOMESTIC.DAILY_DEATH IS '일일사망자';